[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rhpds-portworx"
authors = [{name = "Matt LeVan", email = "mlevan@purestorage.com"}]
dynamic = ["version", "description"]
